Update bashrc and submodules

diff --git a/configs/bashrc b/configs/bashrc
--- a/configs/bashrc
+++ b/configs/bashrc
@@ -3,6 +3,18 @@
 # Vim mode
 set -o vi
 
+# function for going back to root of git repo
+function git_root {
+  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+    cd $(git rev-parse --show-toplevel)
+  else
+    >&2 echo "Error, not inside a git repository"
+    false
+  fi
+}
+
+alias cdgr="git_root"
+
 # Alias neovim if we have it
 if hash "nvim"; then
   alias vim="nvim"
